# Generated by Django 3.0.3 on 2020-02-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('gender', models.CharField(max_length=255)),
                ('hobbies', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
    ]
