# Generated by Django 3.0.3 on 2020-02-26 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='status',
            field=models.CharField(default=datetime.datetime(2020, 2, 26, 7, 21, 57, 572183, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
