# Generated by Django 3.0.3 on 2020-02-26 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trial_app', '0002_users_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='status',
        ),
    ]
